In [1]:
import numpy as np

def gauss_seidel_method(A, b, max_iterations=100, tolerance=1e-10):
    """
    Solve a system of linear equations using the Gauss-Seidel iterative method
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    b (numpy.ndarray): Right-hand side vector
    max_iterations (int): Maximum number of iterations
    tolerance (float): Convergence tolerance
    
    Returns:
    numpy.ndarray: Solution vector
    list: Iteration history
    """
    # Get matrix dimensions
    n = len(b)
    
    # Initialize solution vector
    x = np.zeros_like(b, dtype=float)
    
    # Store iteration results
    iteration_history = []
    
    for iteration in range(max_iterations):
        # Create a copy of the previous iteration
        x_old = x.copy()
        
        # Compute new solution for each variable
        for i in range(n):
            # Sum of terms before the current variable
            sigma1 = sum(A[i, j] * x[j] for j in range(i))
            
            # Sum of terms after the current variable
            sigma2 = sum(A[i, j] * x_old[j] for j in range(i+1, n))
            
            # Update solution using Gauss-Seidel formula
            x[i] = (b[i] - sigma1 - sigma2) / A[i, i]
        
        # Store this iteration's result
        iteration_history.append(x.copy())
        
        # Check convergence
        if np.linalg.norm(x - x_old) < tolerance:
            break
    
    return x, iteration_history

def check_solution(A, b, x):
    """
    Verify the solution by checking Ax = b
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    b (numpy.ndarray): Right-hand side vector
    x (numpy.ndarray): Solution vector
    
    Returns:
    bool: Whether the solution satisfies the equation
    """
    # Compute Ax
    Ax = A @ x
    
    # Check if Ax is close to b
    return np.allclose(Ax, b, rtol=1e-5, atol=1e-8)

def convergence_check(A):
    """
    Check if the matrix is suitable for Gauss-Seidel method
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    
    Returns:
    bool: Whether the matrix is diagonally dominant
    """
    n = A.shape[0]
    for i in range(n):
        # Calculate diagonal dominance
        diagonal = abs(A[i, i])
        row_sum = np.sum(np.abs(A[i, :])) - diagonal
        
        # Check if diagonal is strictly greater than row sum
        if diagonal <= row_sum:
            return False
    return True

# Define the problem
if __name__ == "__main__":
    # Coefficient matrix
    A = np.array([
        [10, -1, -2, 0],
        [-1, 11, -1, 3],
        [2, -1, 10, -1],
        [0, 3, -1, 8]
    ], dtype=float)
    
    # Right-hand side vector
    b = np.array([6, 25, -11, 15], dtype=float)
    
    # Check convergence conditions
    print("Convergence Check:", "Passed" if convergence_check(A) else "Warning: May not converge")
    
    # Solve using Gauss-Seidel Method
    solution, iterations = gauss_seidel_method(A, b)
    
    # Print results
    print("\nCoefficient Matrix A:")
    print(A)
    
    print("\nRight-hand Side Vector b:")
    print(b)
    
    print("\nSolution Vector x:")
    print(solution)
    
    print("\nNumber of Iterations:", len(iterations))
    
    # Verify the solution
    verification = check_solution(A, b, solution)
    print("\nSolution Verification:", "Passed" if verification else "Failed")
    
    # Optional: Print convergence history
    print("\nConvergence History:")
    for i, x in enumerate(iterations, 1):
        print(f"Iteration {i}: {x}")
    
    # Compare with NumPy's direct method for reference
    print("\nNumPy Linear Algebra Solution:")
    numpy_solution = np.linalg.solve(A, b)
    print(numpy_solution)
    

Convergence Check: Passed

Coefficient Matrix A:
[[10. -1. -2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]

Right-hand Side Vector b:
[  6.  25. -11.  15.]

Solution Vector x:
[ 0.61183964  1.96553016 -0.92356688  1.02248033]

Number of Iterations: 11

Solution Verification: Passed

Convergence History:
Iteration 1: [ 0.6         2.32727273 -0.98727273  0.87886364]
Iteration 2: [ 0.63527273  2.00103719 -0.93906446  1.007228  ]
Iteration 3: [ 0.61229083  1.96832203 -0.92490316  1.02126634]
Iteration 4: [ 0.61185157  1.96574085 -0.92366959  1.02238848]
Iteration 5: [ 0.61184017  1.96554592 -0.92357459  1.02247346]
Iteration 6: [ 0.61183967  1.96553134 -0.92356746  1.02247982]
Iteration 7: [ 0.61183964  1.96553025 -0.92356692  1.02248029]
Iteration 8: [ 0.61183964  1.96553017 -0.92356688  1.02248033]
Iteration 9: [ 0.61183964  1.96553016 -0.92356688  1.02248033]
Iteration 10: [ 0.61183964  1.96553016 -0.92356688  1.02248033]
Iteration 11: [ 0.61183964  1.96553016 -0.923