In [1]:
import numpy as np

def jacobi_method(A, b, max_iterations=100, tolerance=1e-10):
    """
    Solve a system of linear equations using the Jacobi iterative method
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    b (numpy.ndarray): Right-hand side vector
    max_iterations (int): Maximum number of iterations
    tolerance (float): Convergence tolerance
    
    Returns:
    numpy.ndarray: Solution vector
    """
    # Get matrix dimensions
    n = len(b)
    
    # Initialize solution vector
    x = np.zeros_like(b, dtype=float)
    
    # Store iteration results
    iteration_history = []
    
    for iteration in range(max_iterations):
        # Create a copy of the previous iteration
        x_old = x.copy()
        
        # Compute new solution for each variable
        for i in range(n):
            # Sum of all terms except the diagonal element
            sigma = sum(A[i, j] * x_old[j] for j in range(n) if i != j)
            
            # Update solution using Jacobi formula
            x[i] = (b[i] - sigma) / A[i, i]
        
        # Store this iteration's result
        iteration_history.append(x.copy())
        
        # Check convergence
        if np.linalg.norm(x - x_old) < tolerance:
            break
    
    return x, iteration_history

def check_solution(A, b, x):
    """
    Verify the solution by checking Ax = b
    
    Parameters:
    A (numpy.ndarray): Coefficient matrix
    b (numpy.ndarray): Right-hand side vector
    x (numpy.ndarray): Solution vector
    
    Returns:
    bool: Whether the solution satisfies the equation
    """
    # Compute Ax
    Ax = A @ x
    
    # Check if Ax is close to b
    return np.allclose(Ax, b, rtol=1e-5, atol=1e-8)

# Define the problem
if __name__ == "__main__":
    # Coefficient matrix
    A = np.array([
        [10, -1, -2, 0],
        [-1, 11, -1, 3],
        [2, -1, 10, -1],
        [0, 3, -1, 8]
    ], dtype=float)
    
    # Right-hand side vector
    b = np.array([6, 25, -11, 15], dtype=float)
    
    # Solve using Jacobi Method
    solution, iterations = jacobi_method(A, b)
    
    # Print results
    print("Coefficient Matrix A:")
    print(A)
    
    print("\nRight-hand Side Vector b:")
    print(b)
    
    print("\nSolution Vector x:")
    print(solution)
    
    print("\nNumber of Iterations:", len(iterations))
    
    # Verify the solution
    verification = check_solution(A, b, solution)
    print("\nSolution Verification:", "Passed" if verification else "Failed")
    
    # Optional: Print convergence history
    print("\nConvergence History:")
    for i, x in enumerate(iterations, 1):
        print(f"Iteration {i}: {x}")
    
    # Compare with NumPy's direct method for reference
    print("\nNumPy Linear Algebra Solution:")
    numpy_solution = np.linalg.solve(A, b)
    print(numpy_solution)

Coefficient Matrix A:
[[10. -1. -2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]

Right-hand Side Vector b:
[  6.  25. -11.  15.]

Solution Vector x:
[ 0.61183964  1.96553016 -0.92356688  1.02248033]

Number of Iterations: 26

Solution Verification: Passed

Convergence History:
Iteration 1: [ 0.6         2.27272727 -1.1         1.875     ]
Iteration 2: [ 0.60727273  1.71590909 -0.80522727  0.88522727]
Iteration 3: [ 0.61054545  2.01330579 -0.96134091  1.13088068]
Iteration 4: [ 0.6090624   1.93241477 -0.90769044  0.99984272]
Iteration 5: [ 0.61170339  1.97289489 -0.92858673  1.03688315]
Iteration 6: [ 0.61157214  1.96113338 -0.92136287  1.01909107]
Iteration 7: [ 0.61184076  1.96663055 -0.92429198  1.02440462]
Iteration 8: [ 0.61180466  1.96493954 -0.92326464  1.02197705]
Iteration 9: [ 0.61184103  1.96569172 -0.92366927  1.02273959]
Iteration 10: [ 0.61183532  1.96545027 -0.92352507  1.02240695]
Iteration 11: [ 0.61184001  1.96555358 -0.92358134  1.02251551]
Iteratio